language: node_js
node_js:
  - 10
branches:
  only:
    - dev
    - master
    - published

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm install

before_script:
  - npm run build
  - npm start -- --silent &
  - npm run e2e

script:
  - npm run e2e

after_success:
  - test $TRAVIS_BRANCH = "published" && ./deploy.sh
