language: node_js
node_js:
  - 10
branches:
  only:
    - dev
    - master

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm install

before_script:
  - npm run build
  - npm start -- --silent &

script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./travis/master.sh; fi
  - if [ "$TRAVIS_BRANCH" = "published" ]; then ./travis/published.sh; fi
