language: node_js
node_js:
  - 10
branches:
  only:
    - dev
    - master
    - published

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm install

before_script:
  - npm run build
  - npm start -- --silent &
  - npm run e2e

after_success:
  - if [ "$TRAVIS_BRANCH" == "published" ]; then ./deploy.sh; fi
