language: node_js
node_js:
  - 10
branches:
  only:
    - dev
    - master
    - published

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm install

before_script:
  - npm run build
  - npm run generate
  - npm start -- --silent &

script:
  - npm run e2e

deploy:
  provider: pages
  local-dir: dist
  repo: popcorn-nantes/popcorn-nantes.github.io
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: published
